# Generated by Django 3.0.2 on 2020-01-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training_programs', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsman',
            name='training_programs',
            field=models.ManyToManyField(blank=True, related_name='sportsman_training_programs', to='training_programs.TrainingProgram', verbose_name='Программы тренировок'),
        ),
        migrations.AddField(
            model_name='gym',
            name='training_programs',
            field=models.ManyToManyField(blank=True, related_name='gym_training_programs', to='training_programs.TrainingProgram', verbose_name='Программы тренировок'),
        ),
    ]
